export const projects = [
  {
    id: 1,
    title: "Movie Database",
    imageName: "project-movies.webp",
    description:
      "TMDB API, endless scroll, background color adapts to hero image dynamically.",
    features: [],
    github: "https://github.com/crvdam/moviedb",
    stack: ["Vue", "Vue Router", "Vite"],
    videoName: "project-movies.webm",
    videoExternalSource: "",
  },
  {
    id: 2,
    title: "Messenger",
    imageName: "project-messenger.webp",
    description:
      "Realtime chat app via WebSockets, user login, chat history. This was my capstone project for CS50Web",
    features: [],
    github: "https://github.com/crvdam/messenger",
    web: "",
    stack: ["JavaScript", "Python", "Django", "WebSockets"],
    videoName: "project-messenger.webm",
    videoExternalSource: "",
  },

  {
    id: 3,
    title: "Real Estate",
    imageName: "project-realestate.webp",
    description:
      "Front-end for a real-estate listings database. Create, edit and delete listings. Search, filter and sort results based on numerous criteria.",
    features: [],
    github: "https://github.com/crvdam/real-estate",
    stack: ["Vue", "Vue Router", "Pinia", "Vite"],
    videoName: "project-realestate.webm",
    videoExternalSource: "",
  },
  {
    id: 4,
    title: "Portrait game",
    imageName: "project-portrait.webp",
    description: "Celebrity portrait guessing game, my first Svelte project.",
    features: [],
    github: "https://github.com/crvdam/celebrity",
    web: "",
    stack: ["TypeScript", "Svelte", "Vite"],
    videoName: "project-portrait.webm",
    videoExternalSource: "",
  },
  {
    id: 5,
    title: "Hangman.py",
    imageName: "project-hangman.webp",
    description:
      "Python hangman game, capstone project for CS50Python. Mind-blowing ASCII art. Uses Merriam-Webster API.",
    features: [],
    github: "://github.com/crvdam/hangman",
    web: "",
    stack: ["Python"],
    videoName: "",
    videoExternalSource: "",
  },
  {
    id: 6,
    title: "Weather",
    imageName: "project-weather.webp",
    description: "Obligatory weather app",
    features: [],
    github: "://github.com/crvdam/weather",
    web: "",
    stack: ["Vue", "Vite"],
    videoName: "",
    videoExternalSource: "",
  },
];
