export const projects = [
  {
    id: 1,
    title: "Movie Database",
    imageName: "project-movies.webp",
    description: "",
    features: [
      "TMDB API",
      "Infinite scroll",
      "Dynamic background color adapts to hero image",
    ],
    github: "https://github.com/crvdam/moviedb",
    stack: ["Vue", "Vue Router", "Vite"],
    videoName: "project-movies.webm",
    videoExternalSource: "",
  },
  {
    id: 2,
    title: "Messenger",
    imageName: "project-messenger.webp",
    description:
      "Fullstack capstone project for Harvard's CS50 Web, written in vanilla JS and Django.",
    features: ["Realtime chat via WebSockets", "User login", "Chat history"],
    github: "https://github.com/crvdam/messenger",
    web: "",
    stack: ["JavaScript", "Python", "Django", "WebSockets"],
    videoName: "project-messenger.webm",
    videoExternalSource: "",
  },

  {
    id: 3,
    title: "Real Estate",
    imageName: "project-realestate.webp",
    description: "Front-end for a real-estate database",
    features: [
      "Routing",
      "Sorting and filtering of items",
      "Create, edit and remove items",
    ],
    github: "https://github.com/crvdam/real-estate",
    stack: ["Vue", "Vue Router", "Pinia", "Vite"],
    videoName: "project-realestate.webm",
    videoExternalSource: "",
  },
  {
    id: 4,
    title: "Portrait game",
    imageName: "project-portrait.webp",
    description: "Celebrity portrait guessing game, my first Svelte project.",
    features: ["TMDB API", "Timer", "Highscore"],
    github: "https://github.com/crvdam/celebrity",
    web: "",
    stack: ["TypeScript", "Svelte", "Vite"],
    videoName: "project-portrait.webm",
    videoExternalSource: "",
  },
];
