export const projects = [
  {
    title: "Messenger",
    imageName: "project-messenger.png",
    text: "Fullstack capstone project for Harvard's CS50 Web, written in vanilla JS and Django.",
    github: "https://github.com/crvdam",
    web: "",
    tech: ["JavaScript", "Python", "Django", "Django Channels"],
    videoName: "",
    videoExternalSource: "",
  },
  {
    title: "Portrait game",
    imageName: "project-portrait.png",
    text: "Celebrity portrait guessing game, my first Svelte project.",
    github: "https://github.com/crvdam/celebrity",
    web: "",
    tech: ["JavaScript", "TypeScript", "Svelte", "Vite"],
    videoName: "",
    videoExternalSource: "",
  },
  {
    title: "Real Estate",
    imageName: "project-realestate.png",
    text: "Search for, filter, create and delete house listings.",
    github: "https://github.com/crvdam/real-estate",
    tech: ["JavaScript", "Vue", "Vue Router", "Pinia", "Vite"],
    videoName: "",
    videoExternalSource: "",
  },
  {
    title: "Movie Database",
    imageName: "project-movies.png",
    text: "Uses TMDB API. Infinite scroll. Background adapts to hero image's colors.",
    github: "https://github.com/crvdam/movies",
    tech: ["JavaScript", "Vue", "Vue Router", "Vite"],
    videoName: "moviedatabase.webm",
    videoExternalSource: "",
  },
];
